/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quadkey;

public class GeoCoordinate2d {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GeoCoordinate2d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GeoCoordinate2d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigQuadKeyJNI.delete_GeoCoordinate2d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeoCoordinate2d() {
    this(SwigQuadKeyJNI.new_GeoCoordinate2d__SWIG_0(), true);
  }

  public GeoCoordinate2d(Longitude longitude, Latitude latitude) {
    this(SwigQuadKeyJNI.new_GeoCoordinate2d__SWIG_1(Longitude.getCPtr(longitude), longitude, Latitude.getCPtr(latitude), latitude), true);
  }

  public GeoCoordinate2d(GeoCoordinate2d other) {
    this(SwigQuadKeyJNI.new_GeoCoordinate2d__SWIG_2(GeoCoordinate2d.getCPtr(other), other), true);
  }

  public GeoCoordinate2d assignGeoCoordinate2d(GeoCoordinate2d rhs) {
    return new GeoCoordinate2d(SwigQuadKeyJNI.GeoCoordinate2d_assignGeoCoordinate2d(swigCPtr, this, GeoCoordinate2d.getCPtr(rhs), rhs), false);
  }

  public void longitude(double longitude) {
    SwigQuadKeyJNI.GeoCoordinate2d_longitude__SWIG_0(swigCPtr, this, longitude);
  }

  public void latitude(double latitude) {
    SwigQuadKeyJNI.GeoCoordinate2d_latitude__SWIG_0(swigCPtr, this, latitude);
  }

  public void longitude(Longitude longitude) {
    SwigQuadKeyJNI.GeoCoordinate2d_longitude__SWIG_1(swigCPtr, this, Longitude.getCPtr(longitude), longitude);
  }

  public void latitude(Latitude latitude) {
    SwigQuadKeyJNI.GeoCoordinate2d_latitude__SWIG_1(swigCPtr, this, Latitude.getCPtr(latitude), latitude);
  }

  public Longitude longitude() {
    return new Longitude(SwigQuadKeyJNI.GeoCoordinate2d_longitude__SWIG_2(swigCPtr, this), false);
  }

  public Latitude latitude() {
    return new Latitude(SwigQuadKeyJNI.GeoCoordinate2d_latitude__SWIG_2(swigCPtr, this), false);
  }

  public boolean near(GeoCoordinate2d other, double eps) {
    return SwigQuadKeyJNI.GeoCoordinate2d_near__SWIG_0(swigCPtr, this, GeoCoordinate2d.getCPtr(other), other, eps);
  }

  public boolean near(GeoCoordinate2d other) {
    return SwigQuadKeyJNI.GeoCoordinate2d_near__SWIG_1(swigCPtr, this, GeoCoordinate2d.getCPtr(other), other);
  }

  public boolean equalTo(GeoCoordinate2d rhs) {
    return SwigQuadKeyJNI.GeoCoordinate2d_equalTo(swigCPtr, this, GeoCoordinate2d.getCPtr(rhs), rhs);
  }

  public boolean notEqualTo(GeoCoordinate2d rhs) {
    return SwigQuadKeyJNI.GeoCoordinate2d_notEqualTo(swigCPtr, this, GeoCoordinate2d.getCPtr(rhs), rhs);
  }

}
