/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quadkey;

public class GeoCoordinateBoundingBox2d {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GeoCoordinateBoundingBox2d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GeoCoordinateBoundingBox2d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigQuadKeyJNI.delete_GeoCoordinateBoundingBox2d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeoCoordinateBoundingBox2d() {
    this(SwigQuadKeyJNI.new_GeoCoordinateBoundingBox2d__SWIG_0(), true);
  }

  public GeoCoordinateBoundingBox2d(GeoCoordinate2d coordinate0, GeoCoordinate2d coordinate1) {
    this(SwigQuadKeyJNI.new_GeoCoordinateBoundingBox2d__SWIG_1(GeoCoordinate2d.getCPtr(coordinate0), coordinate0, GeoCoordinate2d.getCPtr(coordinate1), coordinate1), true);
  }

  public boolean contains(GeoCoordinate2d coordinate) {
    return SwigQuadKeyJNI.GeoCoordinateBoundingBox2d_contains(swigCPtr, this, GeoCoordinate2d.getCPtr(coordinate), coordinate);
  }

  public void growToContain(GeoCoordinate2d coordinate) {
    SwigQuadKeyJNI.GeoCoordinateBoundingBox2d_growToContain(swigCPtr, this, GeoCoordinate2d.getCPtr(coordinate), coordinate);
  }

  public GeoCoordinate2d lowerLeft() {
    return new GeoCoordinate2d(SwigQuadKeyJNI.GeoCoordinateBoundingBox2d_lowerLeft(swigCPtr, this), false);
  }

  public GeoCoordinate2d upperRight() {
    return new GeoCoordinate2d(SwigQuadKeyJNI.GeoCoordinateBoundingBox2d_upperRight(swigCPtr, this), false);
  }

  public GeoCoordinate2d upperLeft() {
    return new GeoCoordinate2d(SwigQuadKeyJNI.GeoCoordinateBoundingBox2d_upperLeft(swigCPtr, this), true);
  }

  public GeoCoordinate2d lowerRight() {
    return new GeoCoordinate2d(SwigQuadKeyJNI.GeoCoordinateBoundingBox2d_lowerRight(swigCPtr, this), true);
  }

  public boolean isValid() {
    return SwigQuadKeyJNI.GeoCoordinateBoundingBox2d_isValid(swigCPtr, this);
  }

}
