/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quadkey;

public class Latitude {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Latitude(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Latitude obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigQuadKeyJNI.delete_Latitude(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double getMinLatitude() {
    return SwigQuadKeyJNI.Latitude_minLatitude_get();
  }

  public static double getMaxLatitude() {
    return SwigQuadKeyJNI.Latitude_maxLatitude_get();
  }

  public Latitude(double val) {
    this(SwigQuadKeyJNI.new_Latitude__SWIG_0(val), true);
  }

  public Latitude(Latitude other) {
    this(SwigQuadKeyJNI.new_Latitude__SWIG_1(Latitude.getCPtr(other), other), true);
  }

  public Latitude assignLatitude(Latitude rhs) {
    return new Latitude(SwigQuadKeyJNI.Latitude_assignLatitude(swigCPtr, this, Latitude.getCPtr(rhs), rhs), false);
  }

  public double val() {
    return SwigQuadKeyJNI.Latitude_val(swigCPtr, this);
  }

  public boolean near(Latitude other, double eps) {
    return SwigQuadKeyJNI.Latitude_near__SWIG_0(swigCPtr, this, Latitude.getCPtr(other), other, eps);
  }

  public boolean near(Latitude other) {
    return SwigQuadKeyJNI.Latitude_near__SWIG_1(swigCPtr, this, Latitude.getCPtr(other), other);
  }

  public boolean lessThan(Latitude rhs) {
    return SwigQuadKeyJNI.Latitude_lessThan(swigCPtr, this, Latitude.getCPtr(rhs), rhs);
  }

  public boolean lessThanOrEqual(Latitude rhs) {
    return SwigQuadKeyJNI.Latitude_lessThanOrEqual(swigCPtr, this, Latitude.getCPtr(rhs), rhs);
  }

  public boolean greaterThan(Latitude rhs) {
    return SwigQuadKeyJNI.Latitude_greaterThan(swigCPtr, this, Latitude.getCPtr(rhs), rhs);
  }

  public boolean greaterThanOrEqual(Latitude rhs) {
    return SwigQuadKeyJNI.Latitude_greaterThanOrEqual(swigCPtr, this, Latitude.getCPtr(rhs), rhs);
  }

  public boolean equalTo(Latitude rhs) {
    return SwigQuadKeyJNI.Latitude_equalTo(swigCPtr, this, Latitude.getCPtr(rhs), rhs);
  }

  public boolean notEqualTo(Latitude rhs) {
    return SwigQuadKeyJNI.Latitude_notEqualTo(swigCPtr, this, Latitude.getCPtr(rhs), rhs);
  }

  public double latitudeDifference(Latitude subtrahend) {
    return SwigQuadKeyJNI.Latitude_latitudeDifference(swigCPtr, this, Latitude.getCPtr(subtrahend), subtrahend);
  }

}
