/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quadkey;

public class Longitude {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Longitude(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Longitude obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigQuadKeyJNI.delete_Longitude(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double getMinLongitude() {
    return SwigQuadKeyJNI.Longitude_minLongitude_get();
  }

  public static double getMaxLongitude() {
    return SwigQuadKeyJNI.Longitude_maxLongitude_get();
  }

  public Longitude(double val) {
    this(SwigQuadKeyJNI.new_Longitude__SWIG_0(val), true);
  }

  public Longitude(Longitude other) {
    this(SwigQuadKeyJNI.new_Longitude__SWIG_1(Longitude.getCPtr(other), other), true);
  }

  public Longitude assignLongitude(Longitude rhs) {
    return new Longitude(SwigQuadKeyJNI.Longitude_assignLongitude(swigCPtr, this, Longitude.getCPtr(rhs), rhs), false);
  }

  public double val() {
    return SwigQuadKeyJNI.Longitude_val(swigCPtr, this);
  }

  public boolean near(Longitude other, double eps) {
    return SwigQuadKeyJNI.Longitude_near__SWIG_0(swigCPtr, this, Longitude.getCPtr(other), other, eps);
  }

  public boolean near(Longitude other) {
    return SwigQuadKeyJNI.Longitude_near__SWIG_1(swigCPtr, this, Longitude.getCPtr(other), other);
  }

  public boolean lessThan(Longitude rhs) {
    return SwigQuadKeyJNI.Longitude_lessThan(swigCPtr, this, Longitude.getCPtr(rhs), rhs);
  }

  public boolean lessThanOrEqual(Longitude rhs) {
    return SwigQuadKeyJNI.Longitude_lessThanOrEqual(swigCPtr, this, Longitude.getCPtr(rhs), rhs);
  }

  public boolean greaterThan(Longitude rhs) {
    return SwigQuadKeyJNI.Longitude_greaterThan(swigCPtr, this, Longitude.getCPtr(rhs), rhs);
  }

  public boolean greaterThanOrEqual(Longitude rhs) {
    return SwigQuadKeyJNI.Longitude_greaterThanOrEqual(swigCPtr, this, Longitude.getCPtr(rhs), rhs);
  }

  public boolean equalTo(Longitude rhs) {
    return SwigQuadKeyJNI.Longitude_equalTo(swigCPtr, this, Longitude.getCPtr(rhs), rhs);
  }

  public boolean notEqualTo(Longitude rhs) {
    return SwigQuadKeyJNI.Longitude_notEqualTo(swigCPtr, this, Longitude.getCPtr(rhs), rhs);
  }

  public double longitudeDifference(Longitude subtrahend) {
    return SwigQuadKeyJNI.Longitude_longitudeDifference(swigCPtr, this, Longitude.getCPtr(subtrahend), subtrahend);
  }

}
