/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quadkey;

public class QuadKeyVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected QuadKeyVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QuadKeyVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigQuadKeyJNI.delete_QuadKeyVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public QuadKeyVector() {
    this(SwigQuadKeyJNI.new_QuadKeyVector__SWIG_0(), true);
  }

  public QuadKeyVector(long n) {
    this(SwigQuadKeyJNI.new_QuadKeyVector__SWIG_1(n), true);
  }

  public long size() {
    return SwigQuadKeyJNI.QuadKeyVector_size(swigCPtr, this);
  }

  public long capacity() {
    return SwigQuadKeyJNI.QuadKeyVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SwigQuadKeyJNI.QuadKeyVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SwigQuadKeyJNI.QuadKeyVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SwigQuadKeyJNI.QuadKeyVector_clear(swigCPtr, this);
  }

  public void add(QuadKey x) {
    SwigQuadKeyJNI.QuadKeyVector_add(swigCPtr, this, QuadKey.getCPtr(x), x);
  }

  public QuadKey get(int i) {
    return new QuadKey(SwigQuadKeyJNI.QuadKeyVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, QuadKey val) {
    SwigQuadKeyJNI.QuadKeyVector_set(swigCPtr, this, i, QuadKey.getCPtr(val), val);
  }

}
