/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quad_key;

public class geo_coordinate_bounding_box2d {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected geo_coordinate_bounding_box2d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(geo_coordinate_bounding_box2d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        quad_key_javaJNI.delete_geo_coordinate_bounding_box2d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public geo_coordinate_bounding_box2d() {
    this(quad_key_javaJNI.new_geo_coordinate_bounding_box2d__SWIG_0(), true);
  }

  public geo_coordinate_bounding_box2d(geo_coordinate2d coordinate0, geo_coordinate2d coordinate1) {
    this(quad_key_javaJNI.new_geo_coordinate_bounding_box2d__SWIG_1(geo_coordinate2d.getCPtr(coordinate0), coordinate0, geo_coordinate2d.getCPtr(coordinate1), coordinate1), true);
  }

  public boolean contains(geo_coordinate2d coordinate) {
    return quad_key_javaJNI.geo_coordinate_bounding_box2d_contains(swigCPtr, this, geo_coordinate2d.getCPtr(coordinate), coordinate);
  }

  public void grow_to_contain(geo_coordinate2d coordinate) {
    quad_key_javaJNI.geo_coordinate_bounding_box2d_grow_to_contain(swigCPtr, this, geo_coordinate2d.getCPtr(coordinate), coordinate);
  }

  public geo_coordinate2d lower_left() {
    return new geo_coordinate2d(quad_key_javaJNI.geo_coordinate_bounding_box2d_lower_left(swigCPtr, this), false);
  }

  public geo_coordinate2d upper_right() {
    return new geo_coordinate2d(quad_key_javaJNI.geo_coordinate_bounding_box2d_upper_right(swigCPtr, this), false);
  }

  public geo_coordinate2d upper_left() {
    return new geo_coordinate2d(quad_key_javaJNI.geo_coordinate_bounding_box2d_upper_left(swigCPtr, this), true);
  }

  public geo_coordinate2d lower_right() {
    return new geo_coordinate2d(quad_key_javaJNI.geo_coordinate_bounding_box2d_lower_right(swigCPtr, this), true);
  }

  public boolean is_valid() {
    return quad_key_javaJNI.geo_coordinate_bounding_box2d_is_valid(swigCPtr, this);
  }

}
