/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quad_key;

public class latitude {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected latitude(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(latitude obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        quad_key_javaJNI.delete_latitude(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double getMin_latitude() {
    return quad_key_javaJNI.latitude_min_latitude_get();
  }

  public static double getMax_latitude() {
    return quad_key_javaJNI.latitude_max_latitude_get();
  }

  public latitude(double val) {
    this(quad_key_javaJNI.new_latitude__SWIG_0(val), true);
  }

  public latitude(latitude other) {
    this(quad_key_javaJNI.new_latitude__SWIG_1(latitude.getCPtr(other), other), true);
  }

  public latitude assign_latitude(latitude rhs) {
    return new latitude(quad_key_javaJNI.latitude_assign_latitude(swigCPtr, this, latitude.getCPtr(rhs), rhs), false);
  }

  public double val() {
    return quad_key_javaJNI.latitude_val(swigCPtr, this);
  }

  public boolean near(latitude other, double eps) {
    return quad_key_javaJNI.latitude_near__SWIG_0(swigCPtr, this, latitude.getCPtr(other), other, eps);
  }

  public boolean near(latitude other) {
    return quad_key_javaJNI.latitude_near__SWIG_1(swigCPtr, this, latitude.getCPtr(other), other);
  }

  public boolean less_than(latitude rhs) {
    return quad_key_javaJNI.latitude_less_than(swigCPtr, this, latitude.getCPtr(rhs), rhs);
  }

  public boolean less_than_or_equal(latitude rhs) {
    return quad_key_javaJNI.latitude_less_than_or_equal(swigCPtr, this, latitude.getCPtr(rhs), rhs);
  }

  public boolean greater_than(latitude rhs) {
    return quad_key_javaJNI.latitude_greater_than(swigCPtr, this, latitude.getCPtr(rhs), rhs);
  }

  public boolean greater_than_or_equal(latitude rhs) {
    return quad_key_javaJNI.latitude_greater_than_or_equal(swigCPtr, this, latitude.getCPtr(rhs), rhs);
  }

  public boolean equal_to(latitude rhs) {
    return quad_key_javaJNI.latitude_equal_to(swigCPtr, this, latitude.getCPtr(rhs), rhs);
  }

  public boolean not_equal_to(latitude rhs) {
    return quad_key_javaJNI.latitude_not_equal_to(swigCPtr, this, latitude.getCPtr(rhs), rhs);
  }

  public double latitude_difference(latitude subtrahend) {
    return quad_key_javaJNI.latitude_latitude_difference(swigCPtr, this, latitude.getCPtr(subtrahend), subtrahend);
  }

}
