/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quad_key;

public class quad_key_vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected quad_key_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(quad_key_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        quad_key_javaJNI.delete_quad_key_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public quad_key_vector() {
    this(quad_key_javaJNI.new_quad_key_vector__SWIG_0(), true);
  }

  public quad_key_vector(long n) {
    this(quad_key_javaJNI.new_quad_key_vector__SWIG_1(n), true);
  }

  public long size() {
    return quad_key_javaJNI.quad_key_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return quad_key_javaJNI.quad_key_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    quad_key_javaJNI.quad_key_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return quad_key_javaJNI.quad_key_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    quad_key_javaJNI.quad_key_vector_clear(swigCPtr, this);
  }

  public void add(quad_key x) {
    quad_key_javaJNI.quad_key_vector_add(swigCPtr, this, quad_key.getCPtr(x), x);
  }

  public quad_key get(int i) {
    return new quad_key(quad_key_javaJNI.quad_key_vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, quad_key val) {
    quad_key_javaJNI.quad_key_vector_set(swigCPtr, this, i, quad_key.getCPtr(val), val);
  }

}
