/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quad_key;

public class quad_key_java {
  public static String type_to_string(type t) {
    return quad_key_javaJNI.type_to_string(t.swigValue());
  }

}
