/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quad_keys;

public class GeoCoordinate2d {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GeoCoordinate2d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GeoCoordinate2d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(GeoCoordinate2d obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        quad_keys_javaJNI.delete_GeoCoordinate2d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeoCoordinate2d() {
    this(quad_keys_javaJNI.new_GeoCoordinate2d__SWIG_0(), true);
  }

  public GeoCoordinate2d(Longitude longitude, Latitude latitude) {
    this(quad_keys_javaJNI.new_GeoCoordinate2d__SWIG_1(Longitude.getCPtr(longitude), longitude, Latitude.getCPtr(latitude), latitude), true);
  }

  public GeoCoordinate2d(GeoCoordinate2d other) {
    this(quad_keys_javaJNI.new_GeoCoordinate2d__SWIG_2(GeoCoordinate2d.getCPtr(other), other), true);
  }

  public GeoCoordinate2d assignGeoCoordinate2d(GeoCoordinate2d rhs) {
    return new GeoCoordinate2d(quad_keys_javaJNI.GeoCoordinate2d_assignGeoCoordinate2d(swigCPtr, this, GeoCoordinate2d.getCPtr(rhs), rhs), false);
  }

  public void set_longitude(double longit) {
    quad_keys_javaJNI.GeoCoordinate2d_set_longitude__SWIG_0(swigCPtr, this, longit);
  }

  public void set_latitude(double latit) {
    quad_keys_javaJNI.GeoCoordinate2d_set_latitude__SWIG_0(swigCPtr, this, latit);
  }

  public void set_longitude(Longitude longit) {
    quad_keys_javaJNI.GeoCoordinate2d_set_longitude__SWIG_1(swigCPtr, this, Longitude.getCPtr(longit), longit);
  }

  public void set_latitude(Latitude latit) {
    quad_keys_javaJNI.GeoCoordinate2d_set_latitude__SWIG_1(swigCPtr, this, Latitude.getCPtr(latit), latit);
  }

  public Longitude get_longitude() {
    return new Longitude(quad_keys_javaJNI.GeoCoordinate2d_get_longitude(swigCPtr, this), false);
  }

  public Latitude get_latitude() {
    return new Latitude(quad_keys_javaJNI.GeoCoordinate2d_get_latitude(swigCPtr, this), false);
  }

  public boolean near(GeoCoordinate2d other, double eps) {
    return quad_keys_javaJNI.GeoCoordinate2d_near__SWIG_0(swigCPtr, this, GeoCoordinate2d.getCPtr(other), other, eps);
  }

  public boolean near(GeoCoordinate2d other) {
    return quad_keys_javaJNI.GeoCoordinate2d_near__SWIG_1(swigCPtr, this, GeoCoordinate2d.getCPtr(other), other);
  }

  public boolean equalTo(GeoCoordinate2d rhs) {
    return quad_keys_javaJNI.GeoCoordinate2d_equalTo(swigCPtr, this, GeoCoordinate2d.getCPtr(rhs), rhs);
  }

  public boolean notEqualTo(GeoCoordinate2d rhs) {
    return quad_keys_javaJNI.GeoCoordinate2d_notEqualTo(swigCPtr, this, GeoCoordinate2d.getCPtr(rhs), rhs);
  }

}
