/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quad_keys;

public class Latitude {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Latitude(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Latitude obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Latitude obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        quad_keys_javaJNI.delete_Latitude(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double getMin_latitude() {
    return quad_keys_javaJNI.Latitude_min_latitude_get();
  }

  public static double getMax_latitude() {
    return quad_keys_javaJNI.Latitude_max_latitude_get();
  }

  public Latitude(double val) {
    this(quad_keys_javaJNI.new_Latitude__SWIG_0(val), true);
  }

  public Latitude(Latitude other) {
    this(quad_keys_javaJNI.new_Latitude__SWIG_1(Latitude.getCPtr(other), other), true);
  }

  public Latitude assignLatitude(Latitude rhs) {
    return new Latitude(quad_keys_javaJNI.Latitude_assignLatitude(swigCPtr, this, Latitude.getCPtr(rhs), rhs), false);
  }

  public double val() {
    return quad_keys_javaJNI.Latitude_val(swigCPtr, this);
  }

  public boolean near(Latitude other, double eps) {
    return quad_keys_javaJNI.Latitude_near__SWIG_0(swigCPtr, this, Latitude.getCPtr(other), other, eps);
  }

  public boolean near(Latitude other) {
    return quad_keys_javaJNI.Latitude_near__SWIG_1(swigCPtr, this, Latitude.getCPtr(other), other);
  }

  public boolean lessThan(Latitude rhs) {
    return quad_keys_javaJNI.Latitude_lessThan(swigCPtr, this, Latitude.getCPtr(rhs), rhs);
  }

  public boolean lessThanOrEqual(Latitude rhs) {
    return quad_keys_javaJNI.Latitude_lessThanOrEqual(swigCPtr, this, Latitude.getCPtr(rhs), rhs);
  }

  public boolean greaterThan(Latitude rhs) {
    return quad_keys_javaJNI.Latitude_greaterThan(swigCPtr, this, Latitude.getCPtr(rhs), rhs);
  }

  public boolean greaterThanOrEqual(Latitude rhs) {
    return quad_keys_javaJNI.Latitude_greaterThanOrEqual(swigCPtr, this, Latitude.getCPtr(rhs), rhs);
  }

  public boolean equalTo(Latitude rhs) {
    return quad_keys_javaJNI.Latitude_equalTo(swigCPtr, this, Latitude.getCPtr(rhs), rhs);
  }

  public boolean notEqualTo(Latitude rhs) {
    return quad_keys_javaJNI.Latitude_notEqualTo(swigCPtr, this, Latitude.getCPtr(rhs), rhs);
  }

  public double latitudeDifference(Latitude subtrahend) {
    return quad_keys_javaJNI.Latitude_latitudeDifference(swigCPtr, this, Latitude.getCPtr(subtrahend), subtrahend);
  }

}
