/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quad_keys;

public class Longitude {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Longitude(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Longitude obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Longitude obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        quad_keys_javaJNI.delete_Longitude(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double getMin_longitude() {
    return quad_keys_javaJNI.Longitude_min_longitude_get();
  }

  public static double getMax_longitude() {
    return quad_keys_javaJNI.Longitude_max_longitude_get();
  }

  public Longitude(double val) {
    this(quad_keys_javaJNI.new_Longitude__SWIG_0(val), true);
  }

  public Longitude(Longitude other) {
    this(quad_keys_javaJNI.new_Longitude__SWIG_1(Longitude.getCPtr(other), other), true);
  }

  public Longitude assignLongitude(Longitude rhs) {
    return new Longitude(quad_keys_javaJNI.Longitude_assignLongitude(swigCPtr, this, Longitude.getCPtr(rhs), rhs), false);
  }

  public double val() {
    return quad_keys_javaJNI.Longitude_val(swigCPtr, this);
  }

  public boolean near(Longitude other, double eps) {
    return quad_keys_javaJNI.Longitude_near__SWIG_0(swigCPtr, this, Longitude.getCPtr(other), other, eps);
  }

  public boolean near(Longitude other) {
    return quad_keys_javaJNI.Longitude_near__SWIG_1(swigCPtr, this, Longitude.getCPtr(other), other);
  }

  public boolean lessThan(Longitude rhs) {
    return quad_keys_javaJNI.Longitude_lessThan(swigCPtr, this, Longitude.getCPtr(rhs), rhs);
  }

  public boolean lessThanOrEqual(Longitude rhs) {
    return quad_keys_javaJNI.Longitude_lessThanOrEqual(swigCPtr, this, Longitude.getCPtr(rhs), rhs);
  }

  public boolean greaterThan(Longitude rhs) {
    return quad_keys_javaJNI.Longitude_greaterThan(swigCPtr, this, Longitude.getCPtr(rhs), rhs);
  }

  public boolean greaterThanOrEqual(Longitude rhs) {
    return quad_keys_javaJNI.Longitude_greaterThanOrEqual(swigCPtr, this, Longitude.getCPtr(rhs), rhs);
  }

  public boolean equalTo(Longitude rhs) {
    return quad_keys_javaJNI.Longitude_equalTo(swigCPtr, this, Longitude.getCPtr(rhs), rhs);
  }

  public boolean notEqualTo(Longitude rhs) {
    return quad_keys_javaJNI.Longitude_notEqualTo(swigCPtr, this, Longitude.getCPtr(rhs), rhs);
  }

  public double longitudeDifference(Longitude subtrahend) {
    return quad_keys_javaJNI.Longitude_longitudeDifference(swigCPtr, this, Longitude.getCPtr(subtrahend), subtrahend);
  }

}
