/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.quad_keys;

public class quad_key_java {
  public static String type_to_string(Type t) {
    return quad_key_javaJNI.type_to_string(t.swigValue());
  }

}
