/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040101
#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } } while (0)


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


#include "quad_keys/quad_key.h"


#include <stdint.h>		// Use the C99 official header


#include <string>


#include <typeinfo>
#include <stdexcept>


#include <vector>
#include <stdexcept>


/* Check for overflow converting to Java int (always signed 32-bit) from (unsigned variable-bit) size_t */
SWIGINTERN jint SWIG_JavaIntFromSize_t(size_t size) {
  static const jint JINT_MAX = 0x7FFFFFFF;
  return (size > (size_t)JINT_MAX) ? -1 : (jint)size;
}


SWIGINTERN jint SWIG_VectorSize(size_t size) {
  jint sz = SWIG_JavaIntFromSize_t(size);
  if (sz == -1)
    throw std::out_of_range("vector size is too large to fit into a Java int");
  return sz;
}

SWIGINTERN std::vector< quad_keys::QuadKey > *new_std_vector_Sl_quad_keys_QuadKey_Sg___SWIG_2(jint count,quad_keys::QuadKey const &value){
        if (count < 0)
          throw std::out_of_range("vector count must be positive");
        return new std::vector< quad_keys::QuadKey >(static_cast<std::vector< quad_keys::QuadKey >::size_type>(count), value);
      }
SWIGINTERN jint std_vector_Sl_quad_keys_QuadKey_Sg__doSize(std::vector< quad_keys::QuadKey > const *self){
        return SWIG_VectorSize(self->size());
      }
SWIGINTERN void std_vector_Sl_quad_keys_QuadKey_Sg__doAdd__SWIG_0(std::vector< quad_keys::QuadKey > *self,std::vector< quad_keys::QuadKey >::value_type const &x){
        self->push_back(x);
      }
SWIGINTERN void std_vector_Sl_quad_keys_QuadKey_Sg__doAdd__SWIG_1(std::vector< quad_keys::QuadKey > *self,jint index,std::vector< quad_keys::QuadKey >::value_type const &x){
        jint size = static_cast<jint>(self->size());
        if (0 <= index && index <= size) {
          self->insert(self->begin() + index, x);
        } else {
          throw std::out_of_range("vector index out of range");
        }
      }
SWIGINTERN std::vector< quad_keys::QuadKey >::value_type std_vector_Sl_quad_keys_QuadKey_Sg__doRemove(std::vector< quad_keys::QuadKey > *self,jint index){
        jint size = static_cast<jint>(self->size());
        if (0 <= index && index < size) {
          quad_keys::QuadKey const old_value = (*self)[index];
          self->erase(self->begin() + index);
          return old_value;
        } else {
          throw std::out_of_range("vector index out of range");
        }
      }
SWIGINTERN std::vector< quad_keys::QuadKey >::value_type const &std_vector_Sl_quad_keys_QuadKey_Sg__doGet(std::vector< quad_keys::QuadKey > *self,jint index){
        jint size = static_cast<jint>(self->size());
        if (index >= 0 && index < size)
          return (*self)[index];
        else
          throw std::out_of_range("vector index out of range");
      }
SWIGINTERN std::vector< quad_keys::QuadKey >::value_type std_vector_Sl_quad_keys_QuadKey_Sg__doSet(std::vector< quad_keys::QuadKey > *self,jint index,std::vector< quad_keys::QuadKey >::value_type const &val){
        jint size = static_cast<jint>(self->size());
        if (index >= 0 && index < size) {
          quad_keys::QuadKey const old_value = (*self)[index];
          (*self)[index] = val;
          return old_value;
        }
        else
          throw std::out_of_range("vector index out of range");
      }
SWIGINTERN void std_vector_Sl_quad_keys_QuadKey_Sg__doRemoveRange(std::vector< quad_keys::QuadKey > *self,jint fromIndex,jint toIndex){
        jint size = static_cast<jint>(self->size());
        if (0 <= fromIndex && fromIndex <= toIndex && toIndex <= size) {
          self->erase(self->begin() + fromIndex, self->begin() + toIndex);
        } else {
          throw std::out_of_range("vector index out of range");
        }
      }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jdouble JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Longitude_1min_1longitude_1get(JNIEnv *jenv, jclass jcls) {
  jdouble jresult = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  result = (double)(double)quad_keys::Longitude::min_longitude;
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Longitude_1max_1longitude_1get(JNIEnv *jenv, jclass jcls) {
  jdouble jresult = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  result = (double)(double)quad_keys::Longitude::max_longitude;
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1Longitude_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jdouble jarg1) {
  jlong jresult = 0 ;
  double arg1 ;
  quad_keys::Longitude *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (double)jarg1; 
  result = (quad_keys::Longitude *)new quad_keys::Longitude(arg1);
  *(quad_keys::Longitude **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1Longitude_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::Longitude *arg1 = 0 ;
  quad_keys::Longitude *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::Longitude **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Longitude const & is null");
    return 0;
  } 
  result = (quad_keys::Longitude *)new quad_keys::Longitude((quad_keys::Longitude const &)*arg1);
  *(quad_keys::Longitude **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Longitude_1assignLongitude(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  quad_keys::Longitude *arg1 = (quad_keys::Longitude *) 0 ;
  quad_keys::Longitude *arg2 = 0 ;
  quad_keys::Longitude *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Longitude **)&jarg1; 
  arg2 = *(quad_keys::Longitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Longitude const & is null");
    return 0;
  } 
  result = (quad_keys::Longitude *) &(arg1)->operator =((quad_keys::Longitude const &)*arg2);
  *(quad_keys::Longitude **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Longitude_1val(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  quad_keys::Longitude *arg1 = (quad_keys::Longitude *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::Longitude **)&jarg1; 
  result = (double)((quad_keys::Longitude const *)arg1)->val();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Longitude_1near_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jdouble jarg3) {
  jboolean jresult = 0 ;
  quad_keys::Longitude *arg1 = (quad_keys::Longitude *) 0 ;
  quad_keys::Longitude *arg2 = 0 ;
  double arg3 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Longitude **)&jarg1; 
  arg2 = *(quad_keys::Longitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Longitude const & is null");
    return 0;
  } 
  arg3 = (double)jarg3; 
  result = (bool)((quad_keys::Longitude const *)arg1)->near((quad_keys::Longitude const &)*arg2,arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Longitude_1near_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Longitude *arg1 = (quad_keys::Longitude *) 0 ;
  quad_keys::Longitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Longitude **)&jarg1; 
  arg2 = *(quad_keys::Longitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Longitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Longitude const *)arg1)->near((quad_keys::Longitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Longitude_1lessThan(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Longitude *arg1 = (quad_keys::Longitude *) 0 ;
  quad_keys::Longitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Longitude **)&jarg1; 
  arg2 = *(quad_keys::Longitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Longitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Longitude const *)arg1)->operator <((quad_keys::Longitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Longitude_1lessThanOrEqual(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Longitude *arg1 = (quad_keys::Longitude *) 0 ;
  quad_keys::Longitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Longitude **)&jarg1; 
  arg2 = *(quad_keys::Longitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Longitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Longitude const *)arg1)->operator <=((quad_keys::Longitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Longitude_1greaterThan(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Longitude *arg1 = (quad_keys::Longitude *) 0 ;
  quad_keys::Longitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Longitude **)&jarg1; 
  arg2 = *(quad_keys::Longitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Longitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Longitude const *)arg1)->operator >((quad_keys::Longitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Longitude_1greaterThanOrEqual(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Longitude *arg1 = (quad_keys::Longitude *) 0 ;
  quad_keys::Longitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Longitude **)&jarg1; 
  arg2 = *(quad_keys::Longitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Longitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Longitude const *)arg1)->operator >=((quad_keys::Longitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Longitude_1equalTo(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Longitude *arg1 = (quad_keys::Longitude *) 0 ;
  quad_keys::Longitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Longitude **)&jarg1; 
  arg2 = *(quad_keys::Longitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Longitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Longitude const *)arg1)->operator ==((quad_keys::Longitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Longitude_1notEqualTo(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Longitude *arg1 = (quad_keys::Longitude *) 0 ;
  quad_keys::Longitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Longitude **)&jarg1; 
  arg2 = *(quad_keys::Longitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Longitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Longitude const *)arg1)->operator !=((quad_keys::Longitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Longitude_1longitudeDifference(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jdouble jresult = 0 ;
  quad_keys::Longitude *arg1 = (quad_keys::Longitude *) 0 ;
  quad_keys::Longitude *arg2 = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Longitude **)&jarg1; 
  arg2 = *(quad_keys::Longitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Longitude const & is null");
    return 0;
  } 
  result = (double)((quad_keys::Longitude const *)arg1)->operator -((quad_keys::Longitude const &)*arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_delete_1Longitude(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  quad_keys::Longitude *arg1 = (quad_keys::Longitude *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(quad_keys::Longitude **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jdouble JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Latitude_1min_1latitude_1get(JNIEnv *jenv, jclass jcls) {
  jdouble jresult = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  result = (double)(double)quad_keys::Latitude::min_latitude;
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Latitude_1max_1latitude_1get(JNIEnv *jenv, jclass jcls) {
  jdouble jresult = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  result = (double)(double)quad_keys::Latitude::max_latitude;
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1Latitude_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jdouble jarg1) {
  jlong jresult = 0 ;
  double arg1 ;
  quad_keys::Latitude *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (double)jarg1; 
  result = (quad_keys::Latitude *)new quad_keys::Latitude(arg1);
  *(quad_keys::Latitude **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1Latitude_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::Latitude *arg1 = 0 ;
  quad_keys::Latitude *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::Latitude **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Latitude const & is null");
    return 0;
  } 
  result = (quad_keys::Latitude *)new quad_keys::Latitude((quad_keys::Latitude const &)*arg1);
  *(quad_keys::Latitude **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Latitude_1assignLatitude(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  quad_keys::Latitude *arg1 = (quad_keys::Latitude *) 0 ;
  quad_keys::Latitude *arg2 = 0 ;
  quad_keys::Latitude *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Latitude **)&jarg1; 
  arg2 = *(quad_keys::Latitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Latitude const & is null");
    return 0;
  } 
  result = (quad_keys::Latitude *) &(arg1)->operator =((quad_keys::Latitude const &)*arg2);
  *(quad_keys::Latitude **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Latitude_1val(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  quad_keys::Latitude *arg1 = (quad_keys::Latitude *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::Latitude **)&jarg1; 
  result = (double)((quad_keys::Latitude const *)arg1)->val();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Latitude_1near_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jdouble jarg3) {
  jboolean jresult = 0 ;
  quad_keys::Latitude *arg1 = (quad_keys::Latitude *) 0 ;
  quad_keys::Latitude *arg2 = 0 ;
  double arg3 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Latitude **)&jarg1; 
  arg2 = *(quad_keys::Latitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Latitude const & is null");
    return 0;
  } 
  arg3 = (double)jarg3; 
  result = (bool)((quad_keys::Latitude const *)arg1)->near((quad_keys::Latitude const &)*arg2,arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Latitude_1near_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Latitude *arg1 = (quad_keys::Latitude *) 0 ;
  quad_keys::Latitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Latitude **)&jarg1; 
  arg2 = *(quad_keys::Latitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Latitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Latitude const *)arg1)->near((quad_keys::Latitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Latitude_1lessThan(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Latitude *arg1 = (quad_keys::Latitude *) 0 ;
  quad_keys::Latitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Latitude **)&jarg1; 
  arg2 = *(quad_keys::Latitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Latitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Latitude const *)arg1)->operator <((quad_keys::Latitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Latitude_1lessThanOrEqual(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Latitude *arg1 = (quad_keys::Latitude *) 0 ;
  quad_keys::Latitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Latitude **)&jarg1; 
  arg2 = *(quad_keys::Latitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Latitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Latitude const *)arg1)->operator <=((quad_keys::Latitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Latitude_1greaterThan(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Latitude *arg1 = (quad_keys::Latitude *) 0 ;
  quad_keys::Latitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Latitude **)&jarg1; 
  arg2 = *(quad_keys::Latitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Latitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Latitude const *)arg1)->operator >((quad_keys::Latitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Latitude_1greaterThanOrEqual(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Latitude *arg1 = (quad_keys::Latitude *) 0 ;
  quad_keys::Latitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Latitude **)&jarg1; 
  arg2 = *(quad_keys::Latitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Latitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Latitude const *)arg1)->operator >=((quad_keys::Latitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Latitude_1equalTo(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Latitude *arg1 = (quad_keys::Latitude *) 0 ;
  quad_keys::Latitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Latitude **)&jarg1; 
  arg2 = *(quad_keys::Latitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Latitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Latitude const *)arg1)->operator ==((quad_keys::Latitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Latitude_1notEqualTo(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::Latitude *arg1 = (quad_keys::Latitude *) 0 ;
  quad_keys::Latitude *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Latitude **)&jarg1; 
  arg2 = *(quad_keys::Latitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Latitude const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::Latitude const *)arg1)->operator !=((quad_keys::Latitude const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_Latitude_1latitudeDifference(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jdouble jresult = 0 ;
  quad_keys::Latitude *arg1 = (quad_keys::Latitude *) 0 ;
  quad_keys::Latitude *arg2 = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Latitude **)&jarg1; 
  arg2 = *(quad_keys::Latitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Latitude const & is null");
    return 0;
  } 
  result = (double)((quad_keys::Latitude const *)arg1)->operator -((quad_keys::Latitude const &)*arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_delete_1Latitude(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  quad_keys::Latitude *arg1 = (quad_keys::Latitude *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(quad_keys::Latitude **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1GeoCoordinate2d_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  quad_keys::GeoCoordinate2d *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (quad_keys::GeoCoordinate2d *)new quad_keys::GeoCoordinate2d();
  *(quad_keys::GeoCoordinate2d **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1GeoCoordinate2d_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  quad_keys::Longitude *arg1 = 0 ;
  quad_keys::Latitude *arg2 = 0 ;
  quad_keys::GeoCoordinate2d *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::Longitude **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Longitude const & is null");
    return 0;
  } 
  arg2 = *(quad_keys::Latitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Latitude const & is null");
    return 0;
  } 
  result = (quad_keys::GeoCoordinate2d *)new quad_keys::GeoCoordinate2d((quad_keys::Longitude const &)*arg1,(quad_keys::Latitude const &)*arg2);
  *(quad_keys::GeoCoordinate2d **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1GeoCoordinate2d_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::GeoCoordinate2d *arg1 = 0 ;
  quad_keys::GeoCoordinate2d *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::GeoCoordinate2d const & is null");
    return 0;
  } 
  result = (quad_keys::GeoCoordinate2d *)new quad_keys::GeoCoordinate2d((quad_keys::GeoCoordinate2d const &)*arg1);
  *(quad_keys::GeoCoordinate2d **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinate2d_1assignGeoCoordinate2d(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  quad_keys::GeoCoordinate2d *arg1 = (quad_keys::GeoCoordinate2d *) 0 ;
  quad_keys::GeoCoordinate2d *arg2 = 0 ;
  quad_keys::GeoCoordinate2d *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1; 
  arg2 = *(quad_keys::GeoCoordinate2d **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::GeoCoordinate2d const & is null");
    return 0;
  } 
  result = (quad_keys::GeoCoordinate2d *) &(arg1)->operator =((quad_keys::GeoCoordinate2d const &)*arg2);
  *(quad_keys::GeoCoordinate2d **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinate2d_1set_1longitude_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  quad_keys::GeoCoordinate2d *arg1 = (quad_keys::GeoCoordinate2d *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1; 
  arg2 = (double)jarg2; 
  (arg1)->set_longitude(arg2);
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinate2d_1set_1latitude_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  quad_keys::GeoCoordinate2d *arg1 = (quad_keys::GeoCoordinate2d *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1; 
  arg2 = (double)jarg2; 
  (arg1)->set_latitude(arg2);
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinate2d_1set_1longitude_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  quad_keys::GeoCoordinate2d *arg1 = (quad_keys::GeoCoordinate2d *) 0 ;
  quad_keys::Longitude *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1; 
  arg2 = *(quad_keys::Longitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Longitude const & is null");
    return ;
  } 
  (arg1)->set_longitude((quad_keys::Longitude const &)*arg2);
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinate2d_1set_1latitude_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  quad_keys::GeoCoordinate2d *arg1 = (quad_keys::GeoCoordinate2d *) 0 ;
  quad_keys::Latitude *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1; 
  arg2 = *(quad_keys::Latitude **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::Latitude const & is null");
    return ;
  } 
  (arg1)->set_latitude((quad_keys::Latitude const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinate2d_1get_1longitude(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::GeoCoordinate2d *arg1 = (quad_keys::GeoCoordinate2d *) 0 ;
  quad_keys::Longitude *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1; 
  result = (quad_keys::Longitude *) &((quad_keys::GeoCoordinate2d const *)arg1)->get_longitude();
  *(quad_keys::Longitude **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinate2d_1get_1latitude(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::GeoCoordinate2d *arg1 = (quad_keys::GeoCoordinate2d *) 0 ;
  quad_keys::Latitude *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1; 
  result = (quad_keys::Latitude *) &((quad_keys::GeoCoordinate2d const *)arg1)->get_latitude();
  *(quad_keys::Latitude **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinate2d_1near_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jdouble jarg3) {
  jboolean jresult = 0 ;
  quad_keys::GeoCoordinate2d *arg1 = (quad_keys::GeoCoordinate2d *) 0 ;
  quad_keys::GeoCoordinate2d *arg2 = 0 ;
  double arg3 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1; 
  arg2 = *(quad_keys::GeoCoordinate2d **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::GeoCoordinate2d const & is null");
    return 0;
  } 
  arg3 = (double)jarg3; 
  result = (bool)((quad_keys::GeoCoordinate2d const *)arg1)->near((quad_keys::GeoCoordinate2d const &)*arg2,arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinate2d_1near_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::GeoCoordinate2d *arg1 = (quad_keys::GeoCoordinate2d *) 0 ;
  quad_keys::GeoCoordinate2d *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1; 
  arg2 = *(quad_keys::GeoCoordinate2d **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::GeoCoordinate2d const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::GeoCoordinate2d const *)arg1)->near((quad_keys::GeoCoordinate2d const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinate2d_1equalTo(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::GeoCoordinate2d *arg1 = (quad_keys::GeoCoordinate2d *) 0 ;
  quad_keys::GeoCoordinate2d *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1; 
  arg2 = *(quad_keys::GeoCoordinate2d **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::GeoCoordinate2d const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::GeoCoordinate2d const *)arg1)->operator ==((quad_keys::GeoCoordinate2d const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinate2d_1notEqualTo(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::GeoCoordinate2d *arg1 = (quad_keys::GeoCoordinate2d *) 0 ;
  quad_keys::GeoCoordinate2d *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1; 
  arg2 = *(quad_keys::GeoCoordinate2d **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::GeoCoordinate2d const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::GeoCoordinate2d const *)arg1)->operator !=((quad_keys::GeoCoordinate2d const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_delete_1GeoCoordinate2d(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  quad_keys::GeoCoordinate2d *arg1 = (quad_keys::GeoCoordinate2d *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1GeoCoordinateBoundingBox2d_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  quad_keys::GeoCoordinateBoundingBox2d *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (quad_keys::GeoCoordinateBoundingBox2d *)new quad_keys::GeoCoordinateBoundingBox2d();
  *(quad_keys::GeoCoordinateBoundingBox2d **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1GeoCoordinateBoundingBox2d_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  quad_keys::GeoCoordinate2d *arg1 = 0 ;
  quad_keys::GeoCoordinate2d *arg2 = 0 ;
  quad_keys::GeoCoordinateBoundingBox2d *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::GeoCoordinate2d **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::GeoCoordinate2d const & is null");
    return 0;
  } 
  arg2 = *(quad_keys::GeoCoordinate2d **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::GeoCoordinate2d const & is null");
    return 0;
  } 
  result = (quad_keys::GeoCoordinateBoundingBox2d *)new quad_keys::GeoCoordinateBoundingBox2d((quad_keys::GeoCoordinate2d const &)*arg1,(quad_keys::GeoCoordinate2d const &)*arg2);
  *(quad_keys::GeoCoordinateBoundingBox2d **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinateBoundingBox2d_1contains(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::GeoCoordinateBoundingBox2d *arg1 = (quad_keys::GeoCoordinateBoundingBox2d *) 0 ;
  quad_keys::GeoCoordinate2d *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::GeoCoordinateBoundingBox2d **)&jarg1; 
  arg2 = *(quad_keys::GeoCoordinate2d **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::GeoCoordinate2d const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::GeoCoordinateBoundingBox2d const *)arg1)->contains((quad_keys::GeoCoordinate2d const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinateBoundingBox2d_1grow_1to_1contain(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  quad_keys::GeoCoordinateBoundingBox2d *arg1 = (quad_keys::GeoCoordinateBoundingBox2d *) 0 ;
  quad_keys::GeoCoordinate2d *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::GeoCoordinateBoundingBox2d **)&jarg1; 
  arg2 = *(quad_keys::GeoCoordinate2d **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::GeoCoordinate2d const & is null");
    return ;
  } 
  (arg1)->grow_to_contain((quad_keys::GeoCoordinate2d const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinateBoundingBox2d_1lower_1left(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::GeoCoordinateBoundingBox2d *arg1 = (quad_keys::GeoCoordinateBoundingBox2d *) 0 ;
  quad_keys::GeoCoordinate2d *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::GeoCoordinateBoundingBox2d **)&jarg1; 
  result = (quad_keys::GeoCoordinate2d *) &((quad_keys::GeoCoordinateBoundingBox2d const *)arg1)->lower_left();
  *(quad_keys::GeoCoordinate2d **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinateBoundingBox2d_1upper_1right(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::GeoCoordinateBoundingBox2d *arg1 = (quad_keys::GeoCoordinateBoundingBox2d *) 0 ;
  quad_keys::GeoCoordinate2d *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::GeoCoordinateBoundingBox2d **)&jarg1; 
  result = (quad_keys::GeoCoordinate2d *) &((quad_keys::GeoCoordinateBoundingBox2d const *)arg1)->upper_right();
  *(quad_keys::GeoCoordinate2d **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinateBoundingBox2d_1upper_1left(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::GeoCoordinateBoundingBox2d *arg1 = (quad_keys::GeoCoordinateBoundingBox2d *) 0 ;
  quad_keys::GeoCoordinate2d result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::GeoCoordinateBoundingBox2d **)&jarg1; 
  result = ((quad_keys::GeoCoordinateBoundingBox2d const *)arg1)->upper_left();
  *(quad_keys::GeoCoordinate2d **)&jresult = new quad_keys::GeoCoordinate2d(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinateBoundingBox2d_1lower_1right(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::GeoCoordinateBoundingBox2d *arg1 = (quad_keys::GeoCoordinateBoundingBox2d *) 0 ;
  quad_keys::GeoCoordinate2d result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::GeoCoordinateBoundingBox2d **)&jarg1; 
  result = ((quad_keys::GeoCoordinateBoundingBox2d const *)arg1)->lower_right();
  *(quad_keys::GeoCoordinate2d **)&jresult = new quad_keys::GeoCoordinate2d(result); 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_GeoCoordinateBoundingBox2d_1is_1valid(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  quad_keys::GeoCoordinateBoundingBox2d *arg1 = (quad_keys::GeoCoordinateBoundingBox2d *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::GeoCoordinateBoundingBox2d **)&jarg1; 
  result = (bool)((quad_keys::GeoCoordinateBoundingBox2d const *)arg1)->is_valid();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_delete_1GeoCoordinateBoundingBox2d(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  quad_keys::GeoCoordinateBoundingBox2d *arg1 = (quad_keys::GeoCoordinateBoundingBox2d *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(quad_keys::GeoCoordinateBoundingBox2d **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jstring JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_type_1to_1string(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jstring jresult = 0 ;
  quad_keys::Type arg1 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (quad_keys::Type)jarg1; 
  result = quad_keys::type_to_string(arg1);
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1quadrant_1south_1west_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  quad_keys::QuadKey::quadrant result;
  
  (void)jenv;
  (void)jcls;
  result = (quad_keys::QuadKey::quadrant)quad_keys::QuadKey::quadrant::south_west;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1quadrant_1south_1east_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  quad_keys::QuadKey::quadrant result;
  
  (void)jenv;
  (void)jcls;
  result = (quad_keys::QuadKey::quadrant)quad_keys::QuadKey::quadrant::south_east;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1quadrant_1north_1west_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  quad_keys::QuadKey::quadrant result;
  
  (void)jenv;
  (void)jcls;
  result = (quad_keys::QuadKey::quadrant)quad_keys::QuadKey::quadrant::north_west;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1quadrant_1north_1east_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  quad_keys::QuadKey::quadrant result;
  
  (void)jenv;
  (void)jcls;
  result = (quad_keys::QuadKey::quadrant)quad_keys::QuadKey::quadrant::north_east;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1QuadKey_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  quad_keys::QuadKey *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (quad_keys::QuadKey *)new quad_keys::QuadKey();
  *(quad_keys::QuadKey **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1QuadKey_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  quad_keys::Type arg1 ;
  quad_keys::QuadKey *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (quad_keys::Type)jarg1; 
  result = (quad_keys::QuadKey *)new quad_keys::QuadKey(arg1);
  *(quad_keys::QuadKey **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1QuadKey_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jlong jarg3, jshort jarg4) {
  jlong jresult = 0 ;
  quad_keys::Type arg1 ;
  std::uint32_t arg2 ;
  std::uint32_t arg3 ;
  std::uint8_t arg4 ;
  quad_keys::QuadKey *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (quad_keys::Type)jarg1; 
  arg2 = (std::uint32_t)jarg2; 
  arg3 = (std::uint32_t)jarg3; 
  arg4 = (std::uint8_t)jarg4; 
  result = (quad_keys::QuadKey *)new quad_keys::QuadKey(arg1,arg2,arg3,arg4);
  *(quad_keys::QuadKey **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1QuadKey_1_1SWIG_13(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::QuadKey *arg1 = 0 ;
  quad_keys::QuadKey *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::QuadKey const & is null");
    return 0;
  } 
  result = (quad_keys::QuadKey *)new quad_keys::QuadKey((quad_keys::QuadKey const &)*arg1);
  *(quad_keys::QuadKey **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1assignQuadKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  quad_keys::QuadKey *arg2 = 0 ;
  quad_keys::QuadKey *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  arg2 = *(quad_keys::QuadKey **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::QuadKey const & is null");
    return 0;
  } 
  result = (quad_keys::QuadKey *) &(arg1)->operator =((quad_keys::QuadKey const &)*arg2);
  *(quad_keys::QuadKey **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1type(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  quad_keys::Type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  result = (quad_keys::Type)((quad_keys::QuadKey const *)arg1)->get_type();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1type_1as_1string(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  result = ((quad_keys::QuadKey const *)arg1)->type_as_string();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1row(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  std::uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  result = (std::uint32_t)((quad_keys::QuadKey const *)arg1)->get_row();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1col(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  std::uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  result = (std::uint32_t)((quad_keys::QuadKey const *)arg1)->get_col();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1depth(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  std::uint8_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  result = (std::uint8_t)((quad_keys::QuadKey const *)arg1)->get_depth();
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1is_1root_1key(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  result = (bool)((quad_keys::QuadKey const *)arg1)->is_root_key();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1parent(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  quad_keys::QuadKey result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  result = ((quad_keys::QuadKey const *)arg1)->get_parent();
  *(quad_keys::QuadKey **)&jresult = new quad_keys::QuadKey(result); 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1is_1my_1ancestor(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  quad_keys::QuadKey *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  arg2 = *(quad_keys::QuadKey **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::QuadKey const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::QuadKey const *)arg1)->is_my_ancestor((quad_keys::QuadKey const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1ancestor(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  jlong jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  std::uint8_t arg2 ;
  quad_keys::QuadKey result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  arg2 = (std::uint8_t)jarg2; 
  result = ((quad_keys::QuadKey const *)arg1)->get_ancestor(arg2);
  *(quad_keys::QuadKey **)&jresult = new quad_keys::QuadKey(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1child(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  quad_keys::QuadKey::quadrant arg2 ;
  quad_keys::QuadKey result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  arg2 = (quad_keys::QuadKey::quadrant)jarg2; 
  result = ((quad_keys::QuadKey const *)arg1)->get_child(arg2);
  *(quad_keys::QuadKey **)&jresult = new quad_keys::QuadKey(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1children(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  std::vector< quad_keys::QuadKey > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  result = ((quad_keys::QuadKey const *)arg1)->get_children();
  *(std::vector< quad_keys::QuadKey > **)&jresult = new std::vector< quad_keys::QuadKey >(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1descendants(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  jlong jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  std::uint8_t arg2 ;
  std::vector< quad_keys::QuadKey > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  arg2 = (std::uint8_t)jarg2; 
  result = ((quad_keys::QuadKey const *)arg1)->get_descendants(arg2);
  *(std::vector< quad_keys::QuadKey > **)&jresult = new std::vector< quad_keys::QuadKey >(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1siblings(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  std::vector< quad_keys::QuadKey > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  result = ((quad_keys::QuadKey const *)arg1)->get_siblings();
  *(std::vector< quad_keys::QuadKey > **)&jresult = new std::vector< quad_keys::QuadKey >(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1neighbors(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  std::vector< quad_keys::QuadKey > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  result = ((quad_keys::QuadKey const *)arg1)->get_neighbors();
  *(std::vector< quad_keys::QuadKey > **)&jresult = new std::vector< quad_keys::QuadKey >(result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1geo_1coordinate_1bounds2d(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  quad_keys::GeoCoordinateBoundingBox2d *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  arg2 = *(quad_keys::GeoCoordinateBoundingBox2d **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::GeoCoordinateBoundingBox2d & is null");
    return ;
  } 
  ((quad_keys::QuadKey const *)arg1)->get_geo_coordinate_bounds2d(*arg2);
}


SWIGEXPORT jstring JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1to_1internal_1string(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  result = ((quad_keys::QuadKey const *)arg1)->to_internal_string();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1from_1internal_1string(JNIEnv *jenv, jclass jcls, jint jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  quad_keys::Type arg1 ;
  std::string *arg2 = 0 ;
  quad_keys::QuadKey result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (quad_keys::Type)jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return 0;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return 0;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  result = quad_keys::QuadKey::from_internal_string(arg1,(std::string const &)*arg2);
  *(quad_keys::QuadKey **)&jresult = new quad_keys::QuadKey(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1key_1from_1longitude_1latitude_1at_1depth(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jobject jarg2_, jshort jarg3) {
  jlong jresult = 0 ;
  quad_keys::Type arg1 ;
  quad_keys::GeoCoordinate2d *arg2 = 0 ;
  std::uint8_t arg3 ;
  quad_keys::QuadKey result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = (quad_keys::Type)jarg1; 
  arg2 = *(quad_keys::GeoCoordinate2d **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::GeoCoordinate2d const & is null");
    return 0;
  } 
  arg3 = (std::uint8_t)jarg3; 
  result = quad_keys::QuadKey::get_key_from_longitude_latitude_at_depth(arg1,(quad_keys::GeoCoordinate2d const &)*arg2,arg3);
  *(quad_keys::QuadKey **)&jresult = new quad_keys::QuadKey(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1get_1keys_1from_1longitude_1latitude_1bounding_1box(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jobject jarg2_, jshort jarg3) {
  jlong jresult = 0 ;
  quad_keys::Type arg1 ;
  quad_keys::GeoCoordinateBoundingBox2d *arg2 = 0 ;
  std::uint8_t arg3 ;
  std::vector< quad_keys::QuadKey > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = (quad_keys::Type)jarg1; 
  arg2 = *(quad_keys::GeoCoordinateBoundingBox2d **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::GeoCoordinateBoundingBox2d const & is null");
    return 0;
  } 
  arg3 = (std::uint8_t)jarg3; 
  result = quad_keys::QuadKey::get_keys_from_longitude_latitude_bounding_box(arg1,(quad_keys::GeoCoordinateBoundingBox2d const &)*arg2,arg3);
  *(std::vector< quad_keys::QuadKey > **)&jresult = new std::vector< quad_keys::QuadKey >(result); 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1max_1depth(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jshort jresult = 0 ;
  quad_keys::Type arg1 ;
  std::uint8_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (quad_keys::Type)jarg1; 
  result = (std::uint8_t)quad_keys::QuadKey::max_depth(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1max_1rows(JNIEnv *jenv, jclass jcls, jint jarg1, jshort jarg2) {
  jlong jresult = 0 ;
  quad_keys::Type arg1 ;
  std::uint8_t arg2 ;
  std::uint32_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (quad_keys::Type)jarg1; 
  arg2 = (std::uint8_t)jarg2; 
  result = (std::uint32_t)quad_keys::QuadKey::max_rows(arg1,arg2);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1max_1cols(JNIEnv *jenv, jclass jcls, jint jarg1, jshort jarg2) {
  jlong jresult = 0 ;
  quad_keys::Type arg1 ;
  std::uint8_t arg2 ;
  std::uint32_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (quad_keys::Type)jarg1; 
  arg2 = (std::uint8_t)jarg2; 
  result = (std::uint32_t)quad_keys::QuadKey::max_cols(arg1,arg2);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1max_1tiles(JNIEnv *jenv, jclass jcls, jint jarg1, jshort jarg2) {
  jobject jresult = 0 ;
  quad_keys::Type arg1 ;
  std::uint8_t arg2 ;
  std::uint64_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (quad_keys::Type)jarg1; 
  arg2 = (std::uint8_t)jarg2; 
  result = (std::uint64_t)quad_keys::QuadKey::max_tiles(arg1,arg2);
  {
    jbyteArray ba = jenv->NewByteArray(9);
    jbyte* bae = jenv->GetByteArrayElements(ba, 0);
    jclass clazz = jenv->FindClass("java/math/BigInteger");
    jmethodID mid = jenv->GetMethodID(clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    jenv->ReleaseByteArrayElements(ba, bae, 0);
    bigint = jenv->NewObject(clazz, mid, ba);
    jenv->DeleteLocalRef(ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1lessThan(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  quad_keys::QuadKey *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  arg2 = *(quad_keys::QuadKey **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::QuadKey const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::QuadKey const *)arg1)->operator <((quad_keys::QuadKey const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1equalTo(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  quad_keys::QuadKey *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  arg2 = *(quad_keys::QuadKey **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::QuadKey const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::QuadKey const *)arg1)->operator ==((quad_keys::QuadKey const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKey_1notEqualTo(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jboolean jresult = 0 ;
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  quad_keys::QuadKey *arg2 = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  arg2 = *(quad_keys::QuadKey **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::QuadKey const & is null");
    return 0;
  } 
  result = (bool)((quad_keys::QuadKey const *)arg1)->operator !=((quad_keys::QuadKey const &)*arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_delete_1QuadKey(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  quad_keys::QuadKey *arg1 = (quad_keys::QuadKey *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(quad_keys::QuadKey **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1QuadKeysVector_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  std::vector< quad_keys::QuadKey > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (std::vector< quad_keys::QuadKey > *)new std::vector< quad_keys::QuadKey >();
  *(std::vector< quad_keys::QuadKey > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1QuadKeysVector_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< quad_keys::QuadKey > *arg1 = 0 ;
  std::vector< quad_keys::QuadKey > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< quad_keys::QuadKey > **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< quad_keys::QuadKey > const & is null");
    return 0;
  } 
  result = (std::vector< quad_keys::QuadKey > *)new std::vector< quad_keys::QuadKey >((std::vector< quad_keys::QuadKey > const &)*arg1);
  *(std::vector< quad_keys::QuadKey > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKeysVector_1capacity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< quad_keys::QuadKey > *arg1 = (std::vector< quad_keys::QuadKey > *) 0 ;
  std::vector< quad_keys::QuadKey >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< quad_keys::QuadKey > **)&jarg1; 
  result = ((std::vector< quad_keys::QuadKey > const *)arg1)->capacity();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKeysVector_1reserve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  std::vector< quad_keys::QuadKey > *arg1 = (std::vector< quad_keys::QuadKey > *) 0 ;
  std::vector< quad_keys::QuadKey >::size_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< quad_keys::QuadKey > **)&jarg1; 
  arg2 = (std::vector< quad_keys::QuadKey >::size_type)jarg2; 
  try {
    (arg1)->reserve(arg2);
  } catch(std::length_error &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
}


SWIGEXPORT jboolean JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKeysVector_1isEmpty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  std::vector< quad_keys::QuadKey > *arg1 = (std::vector< quad_keys::QuadKey > *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< quad_keys::QuadKey > **)&jarg1; 
  result = (bool)((std::vector< quad_keys::QuadKey > const *)arg1)->empty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKeysVector_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::vector< quad_keys::QuadKey > *arg1 = (std::vector< quad_keys::QuadKey > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< quad_keys::QuadKey > **)&jarg1; 
  (arg1)->clear();
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_new_1QuadKeysVector_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  jint arg1 ;
  quad_keys::QuadKey *arg2 = 0 ;
  std::vector< quad_keys::QuadKey > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = jarg1; 
  arg2 = *(quad_keys::QuadKey **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "quad_keys::QuadKey const & is null");
    return 0;
  } 
  try {
    result = (std::vector< quad_keys::QuadKey > *)new_std_vector_Sl_quad_keys_QuadKey_Sg___SWIG_2(SWIG_STD_MOVE(arg1),(quad_keys::QuadKey const &)*arg2);
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  *(std::vector< quad_keys::QuadKey > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKeysVector_1doSize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  std::vector< quad_keys::QuadKey > *arg1 = (std::vector< quad_keys::QuadKey > *) 0 ;
  jint result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< quad_keys::QuadKey > **)&jarg1; 
  try {
    result = std_vector_Sl_quad_keys_QuadKey_Sg__doSize((std::vector< quad_keys::QuadKey > const *)arg1);
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKeysVector_1doAdd_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  std::vector< quad_keys::QuadKey > *arg1 = (std::vector< quad_keys::QuadKey > *) 0 ;
  std::vector< quad_keys::QuadKey >::value_type *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(std::vector< quad_keys::QuadKey > **)&jarg1; 
  arg2 = *(std::vector< quad_keys::QuadKey >::value_type **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< quad_keys::QuadKey >::value_type const & is null");
    return ;
  } 
  std_vector_Sl_quad_keys_QuadKey_Sg__doAdd__SWIG_0(arg1,(quad_keys::QuadKey const &)*arg2);
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKeysVector_1doAdd_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  std::vector< quad_keys::QuadKey > *arg1 = (std::vector< quad_keys::QuadKey > *) 0 ;
  jint arg2 ;
  std::vector< quad_keys::QuadKey >::value_type *arg3 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::vector< quad_keys::QuadKey > **)&jarg1; 
  arg2 = jarg2; 
  arg3 = *(std::vector< quad_keys::QuadKey >::value_type **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< quad_keys::QuadKey >::value_type const & is null");
    return ;
  } 
  try {
    std_vector_Sl_quad_keys_QuadKey_Sg__doAdd__SWIG_1(arg1,SWIG_STD_MOVE(arg2),(quad_keys::QuadKey const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKeysVector_1doRemove(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< quad_keys::QuadKey > *arg1 = (std::vector< quad_keys::QuadKey > *) 0 ;
  jint arg2 ;
  std::vector< quad_keys::QuadKey >::value_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< quad_keys::QuadKey > **)&jarg1; 
  arg2 = jarg2; 
  try {
    result = std_vector_Sl_quad_keys_QuadKey_Sg__doRemove(arg1,SWIG_STD_MOVE(arg2));
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  *(std::vector< quad_keys::QuadKey >::value_type **)&jresult = new std::vector< quad_keys::QuadKey >::value_type(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKeysVector_1doGet(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< quad_keys::QuadKey > *arg1 = (std::vector< quad_keys::QuadKey > *) 0 ;
  jint arg2 ;
  std::vector< quad_keys::QuadKey >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< quad_keys::QuadKey > **)&jarg1; 
  arg2 = jarg2; 
  try {
    result = (std::vector< quad_keys::QuadKey >::value_type *) &std_vector_Sl_quad_keys_QuadKey_Sg__doGet(arg1,SWIG_STD_MOVE(arg2));
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  *(std::vector< quad_keys::QuadKey >::value_type **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKeysVector_1doSet(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  jlong jresult = 0 ;
  std::vector< quad_keys::QuadKey > *arg1 = (std::vector< quad_keys::QuadKey > *) 0 ;
  jint arg2 ;
  std::vector< quad_keys::QuadKey >::value_type *arg3 = 0 ;
  std::vector< quad_keys::QuadKey >::value_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::vector< quad_keys::QuadKey > **)&jarg1; 
  arg2 = jarg2; 
  arg3 = *(std::vector< quad_keys::QuadKey >::value_type **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::vector< quad_keys::QuadKey >::value_type const & is null");
    return 0;
  } 
  try {
    result = std_vector_Sl_quad_keys_QuadKey_Sg__doSet(arg1,SWIG_STD_MOVE(arg2),(quad_keys::QuadKey const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  *(std::vector< quad_keys::QuadKey >::value_type **)&jresult = new std::vector< quad_keys::QuadKey >::value_type(result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_QuadKeysVector_1doRemoveRange(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  std::vector< quad_keys::QuadKey > *arg1 = (std::vector< quad_keys::QuadKey > *) 0 ;
  jint arg2 ;
  jint arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< quad_keys::QuadKey > **)&jarg1; 
  arg2 = jarg2; 
  arg3 = jarg3; 
  try {
    std_vector_Sl_quad_keys_QuadKey_Sg__doRemoveRange(arg1,SWIG_STD_MOVE(arg2),SWIG_STD_MOVE(arg3));
  } catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void JNICALL Java_com_quad_1keys_quad_1keys_1javaJNI_delete_1QuadKeysVector(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  std::vector< quad_keys::QuadKey > *arg1 = (std::vector< quad_keys::QuadKey > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< quad_keys::QuadKey > **)&jarg1; 
  delete arg1;
}


#ifdef __cplusplus
}
#endif

