name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt-setup
      run: sudo apt-get clean && sudo apt update
    - name: apt-install
      run: DEBIAN_FRONTEND=noninteractive sudo apt-get install -y build-essential autotools-dev autoconf-archive libgtest-dev libgmock-dev checkinstall libtool libtool-bin make packaging-dev swig default-jdk python-dev-is-python3 gradle python3-pytest python3-pip
    - name: pip-install
      run: pip3 install --no-input pytest
    - name: preclean
      run: rm -f config.h* configure
    - name: libtoolize
      run: libtoolize --force
    - name: aclocal
      run: aclocal
    - name: autoheader
      run: autoheader
    - name: automake
      run: automake --force-missing --add-missing
    - name: autoreconf
      run: autoreconf -vis
    - name: configure
      run: export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::") && ./configure
    - name: make
      run: export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::") && make
    - name: make check
      run: make check
        # - name: make distcheck
        #   run: make distcheck
    - name: test_java_bindings
      run: cd ./bindings/java/quad_keys && rm -f gradlew gradlew.bat && gradle build; ls -l ${PWD}
    - name: test_python_bindings
      run: cd ./bindings/python && python3 setup.py build_ext --inplace && cp _quad_keys*.so ./quad_keys/ && LD_LIBRARY_PATH=${PWD}/../../build/lib/.libs/ python3 -m pytest .
