name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: autoconf-archive install
      run: sudo apt-get install -y autoconf-archive build-essential
    - name: preclean
      run: rm -f config.h* configure
    - name: libtoolize
      run: libtoolize --force
    - name: aclocal
      run: aclocal
    - name: autoheader
      run: autoheader
    - name: automake
      run: automake --force-missing --add-missing
    - name: autoreconf
      run: autoreconf -vis
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
